# scanner/dast/waf_detector.py
# AGGRESSIVE WAF DETECTION — Identifies WAF presence and type using
# multiple detection strategies: header analysis, response body signatures,
# and behavior-based detection (sending attack payloads and analyzing responses)

import httpx
import re

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["__cfduid", "cf-ray", "cloudflare-nginx", "cloudflare", "cf-cache-status", "cf-connecting-ip"],
        "body": ["cloudflare", "cf-ray", "attention required", "ray id"],
        "cookies": ["__cfduid", "cf_clearance"],
    },
    "Akamai": {
        "headers": ["akamai-ch", "akamai-ghost", "true-client-ip", "x-akamai-transformed", "x-akamai-staging"],
        "body": ["akamai", "access denied", "denied by akamai"],
        "cookies": ["akamai"],
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "awselb", "x-amz-cf-id", "x-amzn-remapped-status"],
        "body": ["awselb", "request id", "request blocked"],
        "cookies": [],
    },
    "ModSecurity": {
        "headers": ["mod_security", "modsecurity", "server: mod_security"],
        "body": ["mod_security", "modsecurity", "not acceptable", "an error was encountered"],
        "cookies": [],
    },
    "Imperva/Incapsula": {
        "headers": ["x-iinfo", "x-cdn", "incap_ses", "visid_incap"],
        "body": ["incapsula", "imperva", "incident id", "access denied"],
        "cookies": ["incap_ses_", "visid_incap_"],
    },
    "F5 BIG-IP ASM": {
        "headers": ["big-ip", "f5", "x-wa-info", "x-ctx"],
        "body": ["big-ip", "f5", "request rejected", "support id"],
        "cookies": ["F5_HT_shrinked"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "sucuri", "server: sucuri"],
        "body": ["sucuri", "cloudproxy", "access denied"],
        "cookies": ["sucuri_cloudproxy"],
    },
    "Wordfence": {
        "headers": ["wordfence"],
        "body": ["wordfence", "this request was blocked", "generated by wordfence"],
        "cookies": [],
    },
    "Fastly": {
        "headers": ["fastly", "x-served-by", "x-cache", "x-cache-hits"],
        "body": ["fastly", "request blocked"],
        "cookies": [],
    },
    "Barracuda": {
        "headers": ["barracuda", "barra"],
        "body": ["barracuda", "blocked by barracuda"],
        "cookies": [],
    },
}

# Attack payloads to trigger WAF responses
WAF_TRIGGER_PAYLOADS = [
    ("?id=1' OR 1=1--", "SQLi trigger"),
    ("?q=<script>alert(1)</script>", "XSS trigger"),
    ("?file=../../../../etc/passwd", "LFI trigger"),
    ("?cmd=; cat /etc/passwd", "CMDI trigger"),
]


class WAFDetector:
    def __init__(self):
        self.signatures = WAF_SIGNATURES

    async def detect(self, client: httpx.AsyncClient, url: str) -> str:
        """Multi-strategy WAF detection."""
        detected = []

        # Strategy 1: Header/body analysis on normal request
        try:
            res = await client.get(url, timeout=15)
            headers_str = str(res.headers).lower()
            body_str = res.text[:2000].lower()
            cookies_str = str(res.cookies).lower()

            for waf_name, sigs in self.signatures.items():
                score = 0
                for h in sigs.get("headers", []):
                    if h.lower() in headers_str:
                        score += 2
                for b in sigs.get("body", []):
                    if b.lower() in body_str:
                        score += 1
                for c in sigs.get("cookies", []):
                    if c.lower() in cookies_str:
                        score += 2
                if score >= 2:
                    detected.append(waf_name)
        except Exception:
            pass

        # Strategy 2: Behavior-based detection (send attack payloads)
        for payload, label in WAF_TRIGGER_PAYLOADS:
            try:
                res = await client.get(f"{url}{payload}", timeout=15)
                if res.status_code in (403, 429, 503):
                    # Check which WAF blocked it
                    headers_str = str(res.headers).lower()
                    body_str = res.text[:2000].lower()

                    for waf_name, sigs in self.signatures.items():
                        for h in sigs.get("headers", []):
                            if h.lower() in headers_str and waf_name not in detected:
                                detected.append(waf_name)
                        for b in sigs.get("body", []):
                            if b.lower() in body_str and waf_name not in detected:
                                detected.append(waf_name)

                    # Generic WAF detection from behavior
                    if not detected and res.status_code == 403:
                        if "blocked" in body_str or "denied" in body_str or "forbidden" in body_str:
                            if "Generic WAF" not in detected:
                                detected.append("Generic WAF")
            except Exception:
                continue

        if detected:
            return detected[0]  # Return the most specific match
        return "Generic"
